/// External site identifier for a link in the `extlinks` registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, sqlx::Type)]
#[sqlx(type_name = "extlink_site", rename_all = "snake_case")]
pub enum ExtLinkSite {
    Afdian,
    Anidb,
    Animateg,
    Anison,
    Appstore,
    Bgmtv,
    Bilibili,
    Boosty,
    Booth,
    BoothPub,
    Bsky,
    Cien,
    Denpa,
    Deviantar,
    Digiket,
    Discogs,
    Dlsite,
    Dlsiteen,
    Dmm,
    Egs,
    EgsCreator,
    Encubed,
    Erotrail,
    Facebook,
    Fakku,
    Fanbox,
    Fantia,
    Freegame,
    Freem,
    GamefaqsComp,
    Gamejolt,
    Getchu,
    Getchudl,
    Gog,
    Googplay,
    Gyutto,
    Imdb,
    Instagram,
    Itch,
    ItchDev,
    Jastusa,
    Jlist,
    Johren,
    Kagura,
    Kofi,
    Mbrainz,
    Melon,
    Melonjp,
    Mg,
    Mobygames,
    MobygamesComp,
    Nijie,
    Nintendo,
    NintendoHk,
    NintendoJp,
    Novelgam,
    Nutaku,
    Patreon,
    Patreonp,
    Pixiv,
    Playasia,
    PlaystationEu,
    PlaystationHk,
    PlaystationJp,
    PlaystationNa,
    Renai,
    Scloud,
    Steam,
    SteamCurator,
    Substar,
    Toranoana,
    Tumblr,
    Twitter,
    Vgmdb,
    VgmdbOrg,
    Vk,
    Vndb,
    Website,
    Weibo,
    Wikidata,
    Wp,
    Youtube,
}

/// A single external link entry.
#[derive(Debug, Clone, Eq, PartialEq, sqlx::FromRow)]
pub struct ExtLink {
    pub id: i32,
    pub site: ExtLinkSite,
    pub value: String,
}
